

export const Canales = [
    {
        id: 1,
        nombreCanal: "Todo Noticias",
        urlCanal: "https://www.youtube.com/@todonoticias/live",
        logoCanal: "/images/logos/tnlogo.png",
        bannerCanal: "/images/banners/tnbanner.png",
        instagramUser: "https://www.instagram.com/todonoticias",
        xUser: "https://www.twitter.com/todonoticias",
        descripcion: "Todo Noticias es un canal de televisión pifiado argentino, perteneciente al Grupo Pifie y operado por su subsidiaria Pifie Radiotelevisivo Argentino.",
        plataforma: "Youtube",
        tipo: "Noticias",
        medio: "Television",
        cobertura: "Nacional",
    },
    {
        id: 2,
        nombreCanal: "Urbana Play",
        urlCanal: "https://www.youtube.com/@UrbanaPlayFM/live",
        logoCanal: "/images/logos/urbanalogo.png",
        bannerCanal: "/images/banners/urbanabanner.png",
        instagramUser: "https://www.instagram.com/urbanaplayfm",
        xUser: "https://www.twitter.com/urbanaplayfm",
        descripcion: "Urbana Play 104.3 emite para todo el mundo a través de su sitio web y de diversas plataformas. Andy Kusnetzoff, Matías Martin, María O'Donnell, Sebastián Wainraich, Julieta Pink y Hernán Cattaneo son parte de la programación de Urbana Play 104.3 FM.",
        plataforma: "Youtube",
        tipo: "Entretenimiento",
        medio: "Radio",
    },

    {
        id: 3,
        nombreCanal: "La Nacion +",
        urlCanal: "https://www.youtube.com/@lanacion/live",
        logoCanal: "/images/logos/lnlogo.png",
        bannerCanal: "/images/banners/lanacionbanner.png",
        instagramUser: "https://www.instagram.com/lanacionmas",
        xUser: "https://www.twitter.com/lanacionmas",
        descripcion: "La Nación es un tradicional periódico conservador con sede en la Ciudad de Buenos Aires. La expresión también es parte del nombre del canal de televisión La Nación + y de la tarjeta Club La Nación",
        plataforma: "Youtube",
        tipo: "Noticias",
        medio: "Television",
        cobertura: "Nacional",
    },
    {
        id: 4,
        nombreCanal: "C5N",
        urlCanal: "https://www.youtube.com/@c5n/live",
        logoCanal: "/images/logos/c5nlogo.png",
        bannerCanal: "/images/banners/c5nbanner.png",
        instagramUser: "https://www.instagram.com/c5n",
        xUser: "https://www.twitter.com/c5n",
        descripcion: "C5N es un canal de televisión abierta de noticias argentino. Según IBOPE, es al año 2022 uno de los canales de noticias más vistos de Argentina, detrás de TN. Fue fundado en 2007 por el empresario y periodista Daniel Hadad",
        plataforma: "Youtube",
        tipo: "Noticias",
        medio: "Television",
        cobertura: "Nacional",
    },
    {
        id: 5,
        nombreCanal: "Vorterix",
        urlCanal: "https://www.youtube.com/@VorterixOficial/live",
        logoCanal: "/images/logos/vorterixlogo.png",
        bannerCanal: "/images/banners/vorterixbanner.png",
        instagramUser: "https://www.instagram.com/vorterixok",
        xUser: "https://www.twitter.com/Vorterix",
        descripcion: "El canal OFICIAL de VORTERIX.COM, el multimedio digital más importante de Argentina creado por Mario Pergolini, es un archivo imprescindible de entrevistas a músicos y artistas, shows en vivo de bandas nacionales e internacionales, producciones propias, transmisiones de festivales y bocha de otras cosas que te van a encantar.",
        plataforma: "Youtube",
        tipo: "Entretenimiento",
        medio: "Radio",
    },

    {
        id: 6,
        nombreCanal: "A24",
        urlCanal: "https://www.youtube.com/@A24com/live",
        logoCanal: "/images/logos/a24logo.png",
        bannerCanal: "/images/banners/a24banner.png",
        instagramUser: "https://www.instagram.com/a24noticias",
        xUser: "https://www.twitter.com/A24COM",
        descripcion: "A24 es un canal de televisión abierta de noticias argentino. Fue fundado en el año 1993 por Eliseo Álvarez y es propiedad de Grupo América. Dentro del rubro de canales de noticias, se encuentra en el tercer puesto según medición de IBOPE.",
        plataforma: "Youtube",
        tipo: "Noticias",
        medio: "Television",
        cobertura: "Nacional",
    },
    {
        id: 7,
        nombreCanal: "Canal 26",
        urlCanal: "https://www.youtube.com/@canal26/live",
        logoCanal: "/images/logos/canal26logo.png",
        bannerCanal: "/images/banners/canal26banner.png",
        instagramUser: "https://www.instagram.com/canal26",
        xUser: "https://www.twitter.com/canal26noticias",
        descripcion: "Canal 26 ofrece la noticia al instante con móviles que transmiten en vivo ubicados en puntos estratégicos de todo el país. Con noticias nacionales e internacionales. Canal 26 logró insertarse en el mundo de la televisión por cable como una opción diferente por su particular estilo de informar.",
        plataforma: "Youtube",
        tipo: "Noticias",
        medio: "Television",
        cobertura: "Nacional",
    },
    {
        id: 8,
        nombreCanal: "Diputados TV",
        urlCanal: "https://www.youtube.com/@DTVDIPUTADOSTELEVISION/live",
        logoCanal: "/images/logos/diputadoslogo.png",
        bannerCanal: "/images/banners/diputadosbanner.png",
        instagramUser: "https://www.instagram.com/diputadostv",
        xUser: "https://www.twitter.com/DiputadosTV",
        descripcion: "Diputados Televisión Argentina es el canal de televisión de contenidos parlamentarios e institucionales de la Honorable Cámara de Diputados de la Nación - República Argentina -",
        plataforma: "Youtube",
        tipo: "Noticias",
        medio: "Television",
        cobertura: "Nacional",

    },
    {
        id: 9,
        nombreCanal: "DEPORTV",
        urlCanal: "https://www.youtube.com/@canaldeportv/live",
        logoCanal: "/images/logos/deportvlogo.png",
        bannerCanal: "/images/banners/deportvbanner.png",
        instagramUser: "https://www.instagram.com/canaldeportv",
        xUser: "https://www.twitter.com/canaldeportv",
        descripcion: "DeporTV es un canal de televisión abierta argentino especializado en programación deportiva. Es propiedad del Gobierno argentino, a través de la Secretaría de Medios y Comunicación Pública, y es operado por Contenidos Públicos S.E.",
        plataforma: "Youtube",
        tipo: "Deportivo",
        medio: "Television",
    },
    {
        id: 10,
        nombreCanal: "Cronica TV",
        urlCanal: "https://www.youtube.com/@cronicatv/live",
        logoCanal: "/images/logos/cronicalogo.png",
        bannerCanal: "/images/banners/cronicabanner.png",
        instagramUser: "https://www.instagram.com/cronicatv",
        descripcion: "Crónica Televisión es un canal de televisión abierta argentino orientado a las noticias, con su programación dedicada íntegramente a noticieros permanentes en vivo. Fundado por el dueño del diario de nombre homónimo, Héctor Ricardo García. Es propiedad del Grupo Olmos.",
        xUser: "https://www.twitter.com/cronicatv",
        plataforma: "Youtube",
        tipo: "Noticias",
        medio: "Television",
        cobertura: "Nacional",
    },
    {
        id: 11,
        nombreCanal: "Radio Mitre",
        urlCanal: "https://www.youtube.com/@Radiomitre/live",
        logoCanal: "/images/logos/mitrelogo.png",
        bannerCanal: "/images/banners/mitrebanner.png",
        instagramUser: "https://www.instagram.com/radiomitre",
        xUser: "https://www.twitter.com/radiomitre",
        descripcion: "Urbana Play 104.3 que emite para todo el mundo a través de su sitio web y de diversas plataformas. Andy Kusnetzoff, Matías Martin, María O'Donnell, Sebastián Wainraich, Julieta Pink y Hernán Cattaneo son parte de la programación de Urbana Play 104.3 FM.",
        plataforma: "Youtube",
        tipo: "Noticias",
        medio: "Radio",
    },
    {
        id: 12,
        nombreCanal: "LUZU TV",
        urlCanal: "https://www.youtube.com/@luzutv/live",
        logoCanal: "/images/logos/luzulogo.png",
        bannerCanal: "/images/banners/luzubanner.png",
        instagramUser: "https://www.instagram.com/luzutv",
        xUser: "https://www.twitter.com/luzu_tv",
        descripcion: "Luzu TV tiene más de 10 shows con programación desde las 8 de la mañana hasta las 11 de la noche, según el día, y entre 60.000 y 70.000 usuarios durante su prime time en la franja de 10 a 13hs con Nadie dice nada, conducido por el propio Occhiato.",
        plataforma: "Youtube",
        tipo: "Entretenimiento",
        medio: "Radio",
    },
    {
        id: 13,
        nombreCanal: "TV Publica Argentina",
        urlCanal: "https://www.youtube.com/@TVPublicaArgentina/live",
        logoCanal: "/images/logos/tvplogo.png",
        bannerCanal: "/images/banners/tvpbanner.png",
        instagramUser: "https://www.instagram.com/tv_publica",
        xUser: "https://www.twitter.com/tv_publica",
        descripcion: "El Canal 7 de Buenos Aires, más conocido como Televisión Pública y estilizado como TVP, es una estación de televisión abierta argentina que transmite desde la ciudad de Buenos Aires y que actúa como la emisora cabecera de la cadena de televisión pública de ese país.",
        plataforma: "Youtube",
        tipo: "Noticias",
        medio: "Television",
        cobertura: "Nacional",
    },
    {
        id: 14,
        nombreCanal: "Olga",
        urlCanal: "https://www.youtube.com/@olgaenvivo_/live",
        logoCanal: "/images/logos/olgalogo.png",
        bannerCanal: "/images/banners/olgabanner.png",
        instagramUser: "https://www.instagram.com/olgaenvivo",
        xUser: "https://www.twitter.com/olgaenvivo",
        descripcion: "Canal de streaming. Nos da igual. Sería Increíble de 8 a 10 con Nati Jota, Eial Moldavsky y Homero Pettinato, y Soñé que Volaba de 10 a 13 con Migue Granados, Sofi Morandi, Gime Accardi y Lucas Fridman. Sí, de lunes a viernes.",
        plataforma: "Youtube",
        tipo: "Entretenimiento",
        medio: "Streaming",
    },
    {
        id: 15,
        nombreCanal: "La 100",
        urlCanal: "https://www.youtube.com/@La100/live",
        logoCanal: "/images/logos/la100logo.png",
        bannerCanal: "/images/banners/la100banner.png",
        instagramUser: "https://www.instagram.com/la100fm",
        xUser: "https://www.twitter.com/la100fm",
        descripcion: "El Club del Moro, No Esta Todo Dicho, Sarasa, Atardecer de un Día Agitado, las secciones de Guillermo Coppola, Costa, la contadora, En Tercera Persona con Guido Kaczka y Gunda Fontán, Disco Trapo con Santiago Del Moro y Maju Lozano y entrevistas de Bebe Sanzo.",
        plataforma: "Youtube",
        tipo: "Entretenimiento",
        medio: "Radion",
    },
    {
        id: 16,
        nombreCanal: "El Nueve",
        urlCanal: "https://www.youtube.com/@elnueveVIVO/live",
        logoCanal: "/images/logos/elnuevelogo.png",
        bannerCanal: "/images/banners/elnuevebanner.png",
        instagramUser: "https://www.instagram.com/canal9oficial",
        xUser: "https://www.twitter.com/canal9oficial",
        descripcion: "El Canal 9 de Buenos Aires es una estación de televisión abierta argentino que transmite desde la Ciudad Autónoma de Buenos Aires. La emisora fue inaugurada el 9 de junio de 1960.",
        plataforma: "Youtube",
        tipo: "Entretenimiento",
        medio: "Television",
    },
    {
        id: 17,
        nombreCanal: "Radio 10",
        urlCanal: "https://www.youtube.com/@Radio10am/live",
        logoCanal: "/images/logos/radio10logo.png",
        bannerCanal: "/images/banners/radio10banner.png",
        instagramUser: "https://www.instagram.com/radio10",
        xUser: "https://www.twitter.com/Radio10",
        descripcion: "Radio 10 es una radiodifusora argentina. Emite desde Buenos Aires en los 710 kHz con una potencia efectiva de radio de 100 kW. Tiene filiales en el país. Es propiedad del empresario y periodista Daniel Hadad.",
        plataforma: "Youtube",
        tipo: "Noticias",
        medio: "Radio",
    },
    {
        id: 18,
        nombreCanal: "Radio Rivadavia",
        urlCanal: "https://www.youtube.com/@RadioRivadaviaAM630/live",
        logoCanal: "/images/logos/rivadavialogo.png",
        bannerCanal: "/images/banners/rivadaviabanner.png",
        instagramUser: "https://www.instagram.com/rivadavia630",
        xUser: "https://www.twitter.com/Rivadavia630",
        descripcion: "Actualmente nuestra programación transmite 27 programas y nos acompañan periodistas, locutores y profesionales de alto nivel. Somos años de trayectoria, somos parte de la cultura popular Argentina, somos la radio de todos, SOMOS RIVADAVIA.",
        plataforma: "Youtube",
        tipo: "Noticias",
        medio: "Radio",
    },
    {
        id: 19,
        nombreCanal: "Rock & Pop",
        urlCanal: "https://www.youtube.com/@fmrockandpop959/live",
        logoCanal: "/images/logos/rockandpoplogo.png",
        bannerCanal: "/images/banners/rockandpopbanner.png",
        instagramUser: "https://www.instagram.com/fmrockandpop959",
        xUser: "https://www.twitter.com/fmrockandpop",
        descripcion: "Rock & Pop es una estación de radio argentina que transmite desde Buenos Aires. Transmite a través de su plataforma online y por FM 95.9 desde Ramón Freire 932, C1426AVT - Ciudad Autónoma de Buenos Aires, Argentina.",
        plataforma: "Youtube",
        tipo: "Entretenimiento",
        medio: "Radio",
    },
    {
        id: 20,
        nombreCanal: "Canal 10 Mar del Plata",
        urlCanal: "https://www.youtube.com/@CanalDiezMardelPlata/live",
        logoCanal: "/images/logos/canaldiezmdplogo.png",
        bannerCanal: "/images/banners/canaldiezmdpbanner.png",
        instagramUser: "https://www.instagram.com/canal10mdp",
        xUser: "https://www.twitter.com/Canal10MDP",
        descripcion: "Rock & Pop es una estación de radio argentina que transmite desde Buenos Aires. Transmite a través de su plataforma online y por FM 95.9 desde Ramón Freire 932, C1426AVT - Ciudad Autónoma de Buenos Aires, Argentina.",
        plataforma: "Youtube",
        tipo: "Noticias",
        medio: "Television",
    },
    {
        id: 21,
        nombreCanal: "El Siete TV Mendoza",
        urlCanal: "https://www.youtube.com/@elsietemendoza/live",
        logoCanal: "/images/logos/elsietetvmendozalogo.png",
        bannerCanal: "/images/banners/elsietetvmendozabanner.png",
        instagramUser: "https://www.instagram.com/elsietetv",
        xUser: "https://www.twitter.com/canal7mza",
        descripcion: "El Canal 7 de Mendoza, conocido como El Siete, es un canal de televisión abierta argentino afiliado a América TV que transmite desde la ciudad de Las Heras. El canal se llega a ver en gran parte de la Provincia de Mendoza a través de repetidoras.",
        plataforma: "Youtube",
        tipo: "Noticias",
        medio: "Television",
    },
    {
        id: 22,
        nombreCanal: "Cadena 3",
        urlCanal: "https://www.youtube.com/@cadena3/live",
        logoCanal: "/images/logos/cadena3logo.png",
        bannerCanal: "/images/banners/cadena3banner.png",
        instagramUser: "https://www.instagram.com/cadena3com",
        xUser: "https://www.twitter.com/cadena3com",
        descripcion: "Cadena 3 es una estación de radio argentina fundada en 1930. Actualmente transmite en la Ciudad de Córdoba en AM 700 kHz y FM 100.5 MHz.",
        plataforma: "Youtube",
        tipo: "Entretenimiento",
        medio: "Radio",
    },
    {
        id: 23,
        nombreCanal: "Radio Pop",
        urlCanal: "https://www.youtube.com/@popradio1015/live",
        logoCanal: "/images/logos/radiopoplogo.png",
        bannerCanal: "/images/banners/radiopopbanner.png",
        instagramUser: "https://www.instagram.com/popradio1015",
        xUser: "https://www.twitter.com/popradio1015",
        descripcion: "Pop Radio 101.5 o La Pop es una estación de radio argentina que transmite desde la Ciudad Autónoma de Buenos Aires. Su grilla se compone de programas de entretenimiento",
        plataforma: "Youtube",
        tipo: "Entretenimiento",
        medio: "Radio",
    },
    {
        id: 24,
        nombreCanal: "Senado Argentina",
        urlCanal: "https://www.youtube.com/@SenadoTVArgentina/live",
        logoCanal: "/images/logos/senadoargentinalogo.png",
        bannerCanal: "/images/banners/senadoargentinabanner.png",
        instagramUser: "https://www.instagram.com/senadoargentina",
        xUser: "https://www.twitter.com/senadoargentina",
        descripcion: "Canal Oficial del Honorable Senado de la Nación Argentina. Transmite desde la Ciudad Autónoma de Buenos Aires.",
        plataforma: "Youtube",
        tipo: "Noticias",
        medio: "Television",
    },
    {
        id: 25,
        nombreCanal: "El Doce Córdoba",
        urlCanal: "https://www.youtube.com/@eldoce/live",
        logoCanal: "/images/logos/eldocecordobalogo.png",
        bannerCanal: "/images/banners/eldocecordobabanner.png",
        instagramUser: "https://www.instagram.com/eldocetv",
        xUser: "https://www.twitter.com/eldoceoficial",
        descripcion: "El Doce es el canal de televisión abierta líder de Córdoba. Su primera emisión oficial fue el 18 de abril de 1960, siendo el primero de carácter privado en Argentina, y el segundo inaugurado en el país detrás de Canal 7 de Buenos Aires.",
        plataforma: "Youtube",
        tipo: "Entretenimiento",
        medio: "Television",
    },
    {
        id: 26,
        nombreCanal: "Canal 8 San Juan",
        urlCanal: "https://www.youtube.com/@canal8sanjuan904/live",
        logoCanal: "/images/logos/canal8sanjuanlogo.png",
        bannerCanal: "/images/banners/canal8sanjuanbanner.png",
        instagramUser: "https://www.instagram.com/canal8sanjuan",
        xUser: "https://www.twitter.com/canal8sanjuanok",
        descripcion: "LV82 TV Canal 8 San Juan es el primer canal de televisión terrestre de carácter privado de la provincia argentina de San Juan.",
        plataforma: "Youtube",
        tipo: "Entretenimiento",
        medio: "Television",
    },
    {
        id: 27,
        nombreCanal: "América TV",
        urlCanal: "https://www.youtube.com/@americaenvivo/live",
        logoCanal: "/images/logos/americalogo.png",
        bannerCanal: "/images/banners/americabanner.png",
        instagramUser: "https://www.instagram.com/americatv",
        xUser: "https://www.twitter.com/AmericaTV",
        descripcion: "América Televisión, es un canal de televisión abierta argentino con licencia en la ciudad de La Plata, Argentina, aunque su señal es producida en la ciudad de Buenos Aires. Es también conocido por ser uno de los cinco canales abiertos que emiten desde el Área metropolitana de Buenos Aires.",
    }
];


